name: Wordle
on:
  schedule:
    - cron: '11 10 * * *'
  push:
    branches: [master]

jobs:
  wordle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1.1.0

      - name: Yarn
        uses: c-hive/gha-yarn-cache@v2
      - run: yarn && yarn start

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Build and test with Rake
        run: |
          gem install twurl

      - name: Setup twurl
        run: |
          echo "$TWURLRC" > ~/.twurlrc

          SIZE=`ls -l video.mp4 | awk '{print $5}'`

          MEDIA_ID=`twurl -H "upload.twitter.com" -X POST "/1.1/media/upload.json" -d "command=INIT&total_bytes=$SIZE&additional_owners=$OWNER&media_category=TWEET_VIDEO&media_type=video/mp4" --file-field media | jq -r '.media_id_string'`

          twurl -H "upload.twitter.com" -X POST "/1.1/media/upload.json" -d "command=APPEND&media_id=$MEDIA_ID&segment_index=0" --file ./video.mp4 --file-field media

          DELAY=`twurl -H "upload.twitter.com" -X POST "/1.1/media/upload.json" -d "command=FINALIZE&media_id=$MEDIA_ID" | jq -r 'if .processing_info.state == "succeeded" then 0 else .processing_info.check_after_secs end'`

          sleep $DELAY
          sleep 5

          TEXT=`cat ./share.txt`
          URL=https://github.com/Falci/wordle-bot

          TWEET_ID=`twurl -d "status=$TEXT" /1.1/statuses/update.json | jq -r '.id_str'`
          twurl -d "in_reply_to_status_id=$TWEET_ID&media_ids=${MEDIA_ID}&status=$URL" /1.1/statuses/update.json

        shell: bash
        env:
          TWURLRC: ${{secrets.TWURLRC}}
          OWNER: ${{secrets.OWNER}}
