name: Wordle
on:
  schedule:
    - cron: '15 6 * * *'
  push:
    branches: [master]

jobs:
  wordle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1.1.0

      - name: Install Yarn
        uses: c-hive/gha-yarn-cache@v2

      - name: Game it out!
        run: yarn && yarn start

      - name: Publish
        run: bash ./script.sh
        shell: bash
        env:
          PEM: ${{secrets.YT_PRIVATE_KEY}}
          ISS: ${{secrets.YT_CLIENT_EMAIL}}
