name: Wordle
on:
  schedule:
    - cron: '15 6 * * *'
  push:
    branches: [master]

jobs:
  wordle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1.1.0

      - name: Install Ynar
        uses: c-hive/gha-yarn-cache@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install twurl
        run: gem install twurl

      - name: Game it out!
        run: yarn && yarn start

      - name: Publish
        run: bash ./script.sh
        shell: bash
        env:
          TWURLRC: ${{secrets.TWURLRC}}
          OWNER: ${{secrets.OWNER}}
          YT_CLIENT_ID: ${{secrets.YT_CLIENT_ID}}
          YT_CLIENT_SECRET: ${{secrets.YT_CLIENT_SECRET}}
          YT_REFRESH_TOKEN: ${{secrets.YT_REFRESH_TOKEN}}
